/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ClientBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "LazyReaderApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "LazyReaderBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "OpenAiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SummaryBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "SupabaseKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}