name: Production Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    environment: lazy-reader-prod-env
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 10.8.0

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: v22.14.0
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Lazy Reader Infra Deploy
        run: |
          cd infra
          pnpm sst secret set OpenAiKey ${{ secrets.OPENAI_KEY }}
          pnpm sst secret set SupabaseUrl ${{ secrets.SUPABASE_URL }}
          pnpm sst secret set SupabaseKey ${{ secrets.SUPABASE_KEY }}
          pnpm sst deploy --stage prod
